{
  "knowledge-article1-title": "What is REITs?",
  "knowledge-article1-content1": "A REIT, or Real Estate Investment Trust, is a company that owns or finances income-producing real estate. Modeled after mutual funds, REITs provide investors of all types regular income streams, diversification and long-term capital appreciation. Its basic connotation operation is to raise funds from investors, and set up real estate investment trust fund, then invest in real estate, real estate related rights, real estate related securities, or other approved the underlying investment by competent authorities. In the same time issue REITs Benefit Securities, in order to clarify the investor’s right to the trust property, the interests of the REITs that received will be shared between the beneficiaries according to the terms of the REITs contract.",
  "knowledge-article1-content2": "Therefore, REITs investors include institutional investors and individual investors. Moreover REITs can be traded like Stock on the open market, meet the needs of institutional investors and individual investors.",
  "knowledge-article1-content3": "In the United States, the real estate securitization commodity has been regarded as the forth type of assets outside stocks, bonds and cash assets by investors, to increase the diversity of asset allocation, and disperse investment risk. In 2005 US congress has passed a bill, that recommend REITs product for enterprise annuity, social security funds, pension funds and insurance funds as their investment products.",
  "knowledge-article2-title": "The main types of REITs",
  "knowledge-article2-content1": "The three main types of REITs are Equity REITs，Mortgage REITs and Hybrid REITs. ",
  "knowledge-article2-content2": "Manage profitable real estate portfolio directly, main income come from the rent, or profits of real estate trading. Equity REITs portfolio is different depending on the business strategy of the differences between common invested property types, including shopping centers, office buildings, industrial, apartments, medical center, restaurant, hotel, recreation areas, or mixed type and so on.",
  "knowledge-article2-content3": "Mortgage REITs is mainly acting as a financial intermediaries, to raise money for all kinds of mortgage, source of income comes from mortgages charge fees and mortgage interest, as well as participation in mortgaged real estate rent and value-added benefits. Because investment targets are based on lending loans or securities, rather than investing in real estate itself, so the interest income is the main source of income, similar to general bonds, and has an inverse relationship between changes in market interest rates.",
  "knowledge-article2-content4": "Hybrid REITs is the combination of equity and mortgage REITs, the main investment targets including real estate and mortgage creditor's rights, the investment ratios set by managers are based on market sentiment and interest rate changes.",
  "knowledge-article3-title": "Why should I invest in REITs?",
  "knowledge-article3-content1": "REITs are total return investments. They typically provide high dividends plus the potential for moderate, long-term capital appreciation. Long-term total returns of REIT stocks are likely to be somewhat less than the returns of higher risk, high-growth stocks and somewhat more than the returns of lower risk bonds.",
  "knowledge-article3-content2": "REITs are required by law to distribute each year to their shareholders at least 90 percent of their taxable income. Thus, REITs tend to be among those companies paying the highest dividends. The dividends come primarily from the relatively stable and predictable stream of contractual rents paid by the tenants who occupy the REIT's properties. Because rental rates tend to rise during periods of inflation, REIT dividends tend to be protected from the long-term corrosive effect of rising prices."
}