{
  "values-card1-title": "Our core value",
  "values-card1-content1": "REITsChain is committed to build ABC (Asset -Backed- Chain), using block Chain technology to provide one-stop solution for Asset securitization and real estate financing services; Use the characteristics of high transparency and high digital asset liquidity of block chain, to create a globally oriented digital asset trading platform.",
  "values-card1-content2": "REITs Chain build and operate ABC digital assets trading platform, and combine trillions of dollars of REITs assets with global tradable digital currency, to provide one-stop global asset allocation and trading platform for institutional investors and individual investors.",
  "values-card2-title": "REITs market size",
  "values-card2-content1": "Potential market size of China REITs in the next 3--5 years will reach several hundred billion RMBs.",
  "values-card2-content2": "After more than 50 years of development, US REITs market from $200 million in 1960, to a total value of $959.4 billion in January 2015. By 2016, global listings of REITs market value will reach $1.5 trillion US Dollars.",
  "values-card2-content3": "According to the total market value of $200 million of listed US REITs in 1960, the US REITs listed market capitalization accounted for 0.16% of the total savings amount in the United States. And in China at the end of 2013 the total savings has amounted to 44.76 trillion RMBs, if according to the size of the American REITs development early in 1960, the future development of REITs scale will reach 70.488 billion RMBs in China at the early stage (greater than the current scale of real estate trust fund of 12.852 billion RMBs). The scale for substitution rate of real estate financing source was 0.47%.",
  "values-card2-content4": "According to the development of US listed REITs ($389 billion in 2010, 17.25% of the total savings), and again assuming that China's savings levels in the future will achieve the same size of US Savings, we can expected that the listed REITs scale in China will reach 7.72 trillion RMBs, an increase of 1.99 trillion RMBs, means that the substitution rate of real estate financing source will rise to 16.34% (above calculation showed, the size of the early development of REITs in China is 70.488 billion RMBs, real estate financing source substitution is at a rate of 0.47%).",
  "values-card3-title": "The outbreak of Block Chain",
  "values-card3-content1": "Using the characteristics of tamper-resistant, non-repudiation and undeniable of block chain, issue commercial real estate project on the block chain using mathematical language, solve the problem of decentralized trust, reduce the cost of credit.",
  "values-card3-content2": "Use the high liquidity of block chain digital assets, the same asset, can ICO in any digital currency transaction market in the world in just a second, solve the cross-border trade and investment liquidity problems, improve the enthusiasm of investment.",
  "values-card4-title": "Intelligent Solutions",
  "values-card4-content1": "Combined with intelligent digital contract, make automatically securitie issueing and financial derivatives trading possible."
}