{
  "values-card1-title": "Our core value",
  "values-card1-content1": "REITsChain is committed to build ABC platform (Asset -Backed- Chain) with block Chain technology to provide one-stop solution service for asset securitization and real estate financing; we use block chain technology which is powered by transparency, liquidity access and cross border payment and settlement capacity to create a global digital assets exchange platform.",
  "values-card1-content2": "The ABC digital assets exchange formed and operated by REITs Chain will combine the power of the global trillion-dollar REITs market and the world-wide traded digital currency to serve the needs of institutional investors and high net worth individual investors for their needs of global assets allocation and assets exchange.",
  "values-card2-title": "REITs market size",
  "values-card2-content1": "The potential market size of REITs in China will reach 500 billion RMB in next 3 to 5 years.",
  "values-card2-content2": "With more than 50 years’ development, US REITs market cap reached a total value of $959.4 billion in January 2015 since 1960s when the initial market cap was only 200 million dollars. By the end of 2016, the global listings of publick traded REITs will reach a market value of more than $1.5 trillion US Dollars.",
  "values-card2-content3": "The market capitalization of US listed REITs in 1960 accounted for 0.16% of its total savings. If the same ratio was applied to China’s total savings of 44.76 trillion RMBs in 2013, REITs market capitalization would reach 70.488 billion RMBs in China at the early stage (greater than the current scale of real estate trust fund of 12.852 billion RMBs). This source of real estate finance only accounted for 0.47% of the total funding source for real estate in China.",
  "values-card2-content4": "Under the assumption that China’s total savings reach the same level of that in U.S., if the ratio of 17.25% for U.S. listed REITs to its savings was applied, the anticipated listed REITs market capitalization would reach 7.72 trillion RMB in next decade. The source of real estate financing coming from REITs would reach 16.34% on the total real estate funding in China.",
  "values-card3-title": "Disruptive Power of Block Chain Technology",
  "values-card3-content1": "With its feature such as tamper-proof, alter-proof of the distributed ledger on block chain, our platform requires the issuers of ABS(REITs) to report the operation results of their core commercial real estate underlining the ABS(REITs) regularly on the block chain. This helps improve transparency, solve the issues on decentralized trust, and substantially reduce the cost of finance and transaction.",
  "values-card3-content2": "As our block chain technology offers users access to a key source of liquidity and digital assets backed by block chain can be exchanged world- wide in just a few seconds, our platform will make the cross-border trade and investment a pleasant experience and fuel interest of global investors.",
  "values-card4-title": "Intelligent Solutions",
  "values-card4-content1": "Our smart contract<span class=\"note-sign\">*</span> solution makes it possible to automate equity issuance and trade financial derivatives.",
  "values-card4-content2": "<span class=\"note-sign\">*</span>A smart contract is an agreement whose execution is both automatable and enforceable. Automatable by computer, although some parts may require human input and control. Enforceable by either legal enforcement of rights and obligations or tamper-proof execution."
}